### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by xialisuper** [alexfeng/InternationalizationScript-iOS#1]
Traceback (most recent call last):
  File "exportToExcelv2.1.py", line 64, in <module>
    main()
  File "exportToExcelv2.1.py", line 62, in main
    exportToExcel()
  File "exportToExcelv2.1.py", line 43, in exportToExcel
    (keys,values) = readKeysAndValuesFromeFilePath(path)
  File "exportToExcelv2.1.py", line 12, in readKeysAndValuesFromeFilePath
    for string in codecs.open(path,'r','utf-8').readlines():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 682, in readlines
    return self.reader.readlines(sizehint)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 591, in readlines
    data = self.read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 480, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

请问是什么原因导致?   另外对于使用storyBoard的项目,有没有把storyBoard也一起导出的可能?

**Comment by alexfeng** [comment]
写的这个指定默认使用utf8编码读取文件，就要求文件的编码格式必须是utf8的，不知道你使用的文件编码是什么格式，gbk还是其他什么的，你可以修改下exportToExcelv2.1.py里的编码格式

**Comment by alexfeng** [comment]
storyBoard项目的多语言处理，都是界面上的，这个如果是在界面上进行多语言处理，这边没有直接导出脚本处理。

**Comment by xialisuper** [comment]
storyBoard也是使用.strings 文件呀.  不过我先研究下为什么我的.strings不支持吧. 感谢回复. 如果有进展我再来.
